using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Input;
using SlurmJobManager.App.Services;
using SlurmJobManager.App.ViewModels.Dialogs;
using SlurmJobManager.App.Views;
using SlurmJobManager.App.Views.Dialogs;
using SlurmJobManager.Core.Interfaces;
using SlurmJobManager.Core.Models;
using SlurmJobManager.Core.Services;

namespace SlurmJobManager.App.ViewModels;

/// <summary>
/// Manages task root directory, task ID, parameter templates and sbatch submission.
/// Supports the multi-task-unit workspace model (tasks.manifest.json) while
/// remaining backward-compatible with single-task task.json layouts.
/// </summary>
public sealed class TaskEditorViewModel : ViewModelBase, IDisposable
{
    private readonly ISshClientService _ssh;
    private readonly ISlurmService _slurm;
    private readonly ITaskStorageService _storage;
    private readonly ITaskBlueprintService _blueprints;
    private Func<string, Task<bool>>? _openInConsoleAsync;

    // ── Local storage root (under <AppBaseDirectory>/Data) ──────────────────
    private static readonly string LocalDataRoot = LocalDataPaths.TasksDirectory;

    private static readonly string PinsFilePath = LocalDataPaths.PinsFilePath;

    // ── Remote source directories ────────────────────────────────────────────
    private static readonly string[] AppSourceDirs = { "/env/preprocess/out", "/env/preprocess/bin" };
    private const string RemoteTemplateDir = "/env/preprocess/out/config";

    // ── Scalar backing fields ────────────────────────────────────────────────
    private string _rootDirectory = string.Empty;
    private string _taskId = string.Empty;
    private string? _selectedTemplate;
    private string _templateContent = string.Empty;
    private string _lastSavedTime = string.Empty;
    private string _remoteWorkDir = string.Empty;
    private string _lastAutoGeneratedRemoteWorkDir = string.Empty;
    private bool _isAutoUpdatingRemoteWorkDir;
    private bool _remoteWorkDirFollowsTaskId = true;
    private string _homeDirectory = string.Empty;
    private string _connectedHostOrAddress = string.Empty;
    private string _connectedUsername = string.Empty;
    private string _appPath = string.Empty;
    private string _saveAsFileName = string.Empty;
    private string _sbatchTemplate = DefaultSbatchTemplate;
    private bool _isBusy;
    private string _statusMessage = string.Empty;
    private string _statusStyleKey = "InfoTextStyle";
    private long? _lastJobId;
    private string _lastSubmitStatusMessage = string.Empty;
    private string _lastSubmitStatusStyleKey = "InfoTextStyle";
    private string _lastSubmitStageLabel = string.Empty;
    private string _lastSubmitNextSteps = string.Empty;
    private string _lastSubmitUnitName = string.Empty;
    private string _lastSubmitRemoteWorkDir = string.Empty;
    private string _lastSubmitRemoteStdoutPath = string.Empty;
    private string _lastSubmitRemoteStderrPath = string.Empty;
    private string _lastSubmitLocalScriptPath = string.Empty;
    private string _lastSubmitLocalSubmitLogPath = string.Empty;
    private TaskFileEntry? _selectedTaskFile;
    private string _currentTaskFilesPath = string.Empty;

    // ── TaskId directory validation ──────────────────────────────────────────
    private bool? _taskIdDirectoryExists;
    private string _taskIdDirectoryStatus = string.Empty;
    private CancellationTokenSource? _taskIdValidationCts;

    // ── Workspace / active task-unit state ──────────────────────────────────
    // Each TaskId has exactly ONE active task unit.  Legacy workspaces with
    // multiple units are migrated at load time (user picks one; the rest are
    // discarded from the active editing session but remain in the saved file
    // until the next explicit Save).
    private TaskUnitViewModel? _selectedTaskUnit;

    // ── Properties ───────────────────────────────────────────────────────────

    public string RootDirectory
    {
        get => _rootDirectory;
        set
        {
            var expanded = ExpandHomePath(value);
            if (SetField(ref _rootDirectory, expanded))
            {
                OnPropertyChanged(nameof(RootDirectoryDisplay));
                CommandManager.InvalidateRequerySuggested();
                TryAutoFillRemoteWorkDir();
            }
        }
    }

    public string TaskId
    {
        get => _taskId;
        set
        {
            if (SetField(ref _taskId, value))
            {
                CommandManager.InvalidateRequerySuggested();
                TryAutoFillRemoteWorkDir();
                ScheduleTaskIdDirectoryCheck();
                OnPropertyChanged(nameof(TaskContextSummary));
            }
        }
    }

    public string? SelectedTemplate
    {
        get => _selectedTemplate;
        set
        {
            if (SetField(ref _selectedTemplate, value))
            {
                RebuildFilteredTemplateList();
                if (!string.IsNullOrEmpty(value) && TemplateDisplayList.Contains(value))
                {
                    LoadSelectedRemoteTemplate();
                    SaveAsFileName = value;
                }
            }
        }
    }

    public string TemplateContent   { get => _templateContent;   set => SetField(ref _templateContent, value); }
    public string LastSavedTime     { get => _lastSavedTime;     set => SetField(ref _lastSavedTime, value); }

    public string RemoteWorkDir
    {
        get => _remoteWorkDir;
        set
        {
            var expanded = ExpandHomePath(value);
            if (SetField(ref _remoteWorkDir, expanded))
            {
                OnPropertyChanged(nameof(RemoteWorkDirDisplay));
                OnPropertyChanged(nameof(TaskFilesRootPathDisplay));
                OnPropertyChanged(nameof(TaskContextSummary));
                if (!_isAutoUpdatingRemoteWorkDir)
                {
                    var normalizedCurrent = NormalizeRemotePath(expanded);
                    var normalizedAuto = NormalizeRemotePath(BuildAutoRemoteWorkDir());
                    _remoteWorkDirFollowsTaskId =
                        string.IsNullOrWhiteSpace(normalizedCurrent)
                        || (!string.IsNullOrWhiteSpace(normalizedAuto)
                            && string.Equals(normalizedCurrent, normalizedAuto, StringComparison.Ordinal));
                }

                if (string.IsNullOrWhiteSpace(CurrentTaskFilesPath))
                {
                    CurrentTaskFilesPath = expanded;
                }
            }
        }
    }

    public string AppPath
    {
        get => _appPath;
        set { if (SetField(ref _appPath, value)) { RebuildFilteredAppList(); CommandManager.InvalidateRequerySuggested(); } }
    }

    public string SaveAsFileName
    {
        get => _saveAsFileName;
        set => SetField(ref _saveAsFileName, value);
    }

    public string SbatchTemplate    { get => _sbatchTemplate;    set => SetField(ref _sbatchTemplate, value); }
    public bool IsBusy
    {
        get => _isBusy;
        set
        {
            if (SetField(ref _isBusy, value))
            {
                OnPropertyChanged(nameof(EffectiveStatusStyleKey));
                OnPropertyChanged(nameof(EffectiveStatusMessage));
                OnPropertyChanged(nameof(TaskContextSummary));
            }
        }
    }
    public string StatusMessage
    {
        get => _statusMessage;
        set
        {
            if (SetField(ref _statusMessage, value))
            {
                OnPropertyChanged(nameof(EffectiveStatusMessage));
                OnPropertyChanged(nameof(TaskContextSummary));
            }
        }
    }
    public string StatusStyleKey
    {
        get => _statusStyleKey;
        private set
        {
            if (SetField(ref _statusStyleKey, value))
                OnPropertyChanged(nameof(EffectiveStatusStyleKey));
        }
    }
    public long? LastJobId          { get => _lastJobId;         set { SetField(ref _lastJobId, value); OnPropertyChanged(nameof(LastJobIdText)); } }
    public string LastJobIdText     => _lastJobId.HasValue ? string.Format(L("Task.LastJobId"), _lastJobId) : string.Empty;
    public bool HasLastSubmitDiagnostics
        => !string.IsNullOrWhiteSpace(_lastSubmitStatusMessage)
           || !string.IsNullOrWhiteSpace(_lastSubmitLocalScriptPath)
           || !string.IsNullOrWhiteSpace(_lastSubmitRemoteWorkDir);
    public string LastSubmitStatusMessage
    {
        get => _lastSubmitStatusMessage;
        private set => SetField(ref _lastSubmitStatusMessage, value);
    }

    public string LastSubmitStatusStyleKey
    {
        get => _lastSubmitStatusStyleKey;
        private set => SetField(ref _lastSubmitStatusStyleKey, value);
    }

    public string LastSubmitStageLabel
    {
        get => _lastSubmitStageLabel;
        private set => SetField(ref _lastSubmitStageLabel, value);
    }

    public string LastSubmitNextSteps
    {
        get => _lastSubmitNextSteps;
        private set => SetField(ref _lastSubmitNextSteps, value);
    }

    public string LastSubmitUnitName
    {
        get => _lastSubmitUnitName;
        private set => SetField(ref _lastSubmitUnitName, value);
    }

    public string LastSubmitRemoteWorkDir
    {
        get => _lastSubmitRemoteWorkDir;
        private set => SetField(ref _lastSubmitRemoteWorkDir, value);
    }

    public string LastSubmitRemoteWorkDirDisplay => CollapseHomePath(_lastSubmitRemoteWorkDir);
    public string LastSubmitRemoteStdoutPath
    {
        get => _lastSubmitRemoteStdoutPath;
        private set => SetField(ref _lastSubmitRemoteStdoutPath, value);
    }

    public string LastSubmitRemoteStdoutPathDisplay => CollapseHomePath(_lastSubmitRemoteStdoutPath);
    public string LastSubmitRemoteStderrPath
    {
        get => _lastSubmitRemoteStderrPath;
        private set => SetField(ref _lastSubmitRemoteStderrPath, value);
    }

    public string LastSubmitRemoteStderrPathDisplay => CollapseHomePath(_lastSubmitRemoteStderrPath);
    public string LastSubmitLocalScriptPath
    {
        get => _lastSubmitLocalScriptPath;
        private set => SetField(ref _lastSubmitLocalScriptPath, value);
    }

    public string LastSubmitLocalSubmitLogPath
    {
        get => _lastSubmitLocalSubmitLogPath;
        private set => SetField(ref _lastSubmitLocalSubmitLogPath, value);
    }

    public string EffectiveStatusStyleKey => IsBusy ? "BusyTextStyle" : StatusStyleKey;
    public string EffectiveStatusMessage
    {
        get
        {
            if (!string.IsNullOrWhiteSpace(StatusMessage))
                return StatusMessage;
            return IsBusy ? L("Status.Loading") : string.Empty;
        }
    }

    public string TaskIdDirectoryStatus
    {
        get => _taskIdDirectoryStatus;
        set => SetField(ref _taskIdDirectoryStatus, value);
    }

    public string CurrentTaskFilesPath
    {
        get => _currentTaskFilesPath;
        set
        {
            var expanded = ExpandHomePath(value);
            if (SetField(ref _currentTaskFilesPath, expanded))
            {
                OnPropertyChanged(nameof(CurrentTaskFilesPathDisplay));
                OnPropertyChanged(nameof(TaskContextSummary));
            }
        }
    }

    public string RootDirectoryDisplay
    {
        get => CollapseHomePath(RootDirectory);
        set => RootDirectory = value;
    }

    public string RemoteWorkDirDisplay
    {
        get => CollapseHomePath(RemoteWorkDir);
        set => RemoteWorkDir = value;
    }

    public string CurrentTaskFilesPathDisplay
    {
        get => CollapseHomePath(CurrentTaskFilesPath);
        set => CurrentTaskFilesPath = value;
    }

    public string TaskFilesRootPathDisplay => CollapseHomePath(RemoteWorkDir);
    public string TaskContextSummary
    {
        get
        {
            var taskId = string.IsNullOrWhiteSpace(TaskId) ? "-" : TaskId.Trim();
            var workDir = string.IsNullOrWhiteSpace(RemoteWorkDirDisplay) ? "-" : RemoteWorkDirDisplay;
            var filePath = string.IsNullOrWhiteSpace(CurrentTaskFilesPathDisplay) ? "-" : CurrentTaskFilesPathDisplay;
            var status = IsBusy ? L("Status.Loading") : L("Status.Ready");
            return string.Format(L("Task.ContextSummary"), taskId, workDir, filePath, status);
        }
    }

    public TaskFileEntry? SelectedTaskFile
    {
        get => _selectedTaskFile;
        set => SetField(ref _selectedTaskFile, value);
    }

    // ── Task-unit management ─────────────────────────────────────────────────

    /// <summary>
    /// The single active task unit for the current workspace.
    /// Binding alias exposed to the view.
    /// </summary>
    public TaskUnitViewModel? ActiveUnit => _selectedTaskUnit;

    /// <summary>All task units in the current workspace (exposed for the unit-selector ComboBox).</summary>
    public ObservableCollection<TaskUnitViewModel> TaskUnits { get; } = new();

    /// <summary>Commands for adding / removing task units from the unit selector.</summary>
    public ICommand AddTaskUnitCommand    { get; private set; } = null!;
    public ICommand RemoveTaskUnitCommand { get; private set; } = null!;

    /// <summary>The active (and only) task unit for the current workspace.</summary>
    public TaskUnitViewModel? SelectedTaskUnit
    {
        get => _selectedTaskUnit;
        set
        {
            if (SetField(ref _selectedTaskUnit, value))
            {
                SyncFromSelectedUnit();
                OnPropertyChanged(nameof(ActiveUnit));
                CommandManager.InvalidateRequerySuggested();
            }
        }
    }

    // ── Collections (legacy / shared) ────────────────────────────────────────

    public ObservableCollection<string> AppDisplayList      { get; } = new();
    public ObservableCollection<string> PinnedApps          { get; } = new();
    public ObservableCollection<string> FilteredAppList     { get; } = new();

    public ObservableCollection<string> TemplateDisplayList  { get; } = new();
    public ObservableCollection<string> PinnedTemplates      { get; } = new();
    public ObservableCollection<string> FilteredTemplateList { get; } = new();

    /// <summary>Key/value extra parameters (bound to the active task unit).</summary>
    public ObservableCollection<ParameterEntry> Parameters { get; } = new();

    public ObservableCollection<TaskFileEntry> TaskFiles { get; } = new();

    // ── Commands ─────────────────────────────────────────────────────────────

    public ICommand BrowseRootDirectoryCommand        { get; }
    public ICommand NewTaskIdCommand                  { get; }
    public ICommand SaveTaskCommand                   { get; }
    public ICommand LoadTaskCommand                   { get; }
    public ICommand SaveParamFileCommand              { get; }
    public ICommand SubmitJobCommand                  { get; }
    public ICommand AddParamCommand                   { get; }
    public ICommand RemoveParamCommand                { get; }
    public ICommand RefreshAppCandidatesCommand       { get; }
    public ICommand TogglePinAppCommand               { get; }
    public ICommand RefreshTemplateCandidatesCommand  { get; }
    public ICommand TogglePinTemplateCommand          { get; }
    public ICommand RefreshTaskFilesCommand           { get; }
    public ICommand OpenTaskFileCommand               { get; }
    public ICommand GoUpTaskFilesPathCommand          { get; }
    public ICommand OpenInConsoleCommand              { get; }
    public ICommand OpenLastSubmitScriptCommand       { get; }
    public ICommand OpenLastSubmitLogCommand          { get; }
    public ICommand OpenLastStdoutCommand             { get; }
    public ICommand OpenLastStderrCommand             { get; }
    public ICommand OpenLastSubmitWorkDirInConsoleCommand { get; }
    public ICommand RefreshLastSubmitWorkDirFilesCommand { get; }

    /// <summary>Opens the Command Builder dialog for the active task unit.</summary>
    public ICommand OpenCommandBuilderCommand { get; }
    public ICommand SaveAsBlueprintCommand { get; }
    public ICommand CreateFromBlueprintCommand { get; }

    // ── Constructor ──────────────────────────────────────────────────────────

    public TaskEditorViewModel(
        ISshClientService ssh,
        ISlurmService slurm,
        ITaskStorageService storage,
        ITaskBlueprintService blueprints,
        Func<string, Task<bool>>? openInConsoleAsync = null)
    {
        _ssh     = ssh     ?? throw new ArgumentNullException(nameof(ssh));
        _slurm   = slurm   ?? throw new ArgumentNullException(nameof(slurm));
        _storage = storage ?? throw new ArgumentNullException(nameof(storage));
        _blueprints = blueprints ?? throw new ArgumentNullException(nameof(blueprints));
        _openInConsoleAsync = openInConsoleAsync;

        BrowseRootDirectoryCommand       = new AsyncRelayCommand(BrowseRootDirectoryAsync, () => _ssh.IsConnected);
        NewTaskIdCommand                 = new RelayCommand(GenerateNewTaskId, () => _taskIdDirectoryExists != true);
        SaveTaskCommand                  = new AsyncRelayCommand(SaveTaskAsync,     () => !IsBusy);
        LoadTaskCommand                  = new AsyncRelayCommand(LoadTaskAsync,     () => !IsBusy);
        SaveParamFileCommand             = new AsyncRelayCommand(SaveParamFileAsync, () => !IsBusy);
        SubmitJobCommand                 = new AsyncRelayCommand(SubmitJobAsync,    CanSubmit);
        AddParamCommand                  = new RelayCommand(AddParam);
        RemoveParamCommand               = new RelayCommand<ParameterEntry>(p => { if (p != null) Parameters.Remove(p); });
        RefreshAppCandidatesCommand      = new AsyncRelayCommand(RefreshAppCandidatesAsync,       () => _ssh.IsConnected && !IsBusy);
        TogglePinAppCommand              = new RelayCommand(TogglePinApp,                          () => !string.IsNullOrWhiteSpace(AppPath));
        RefreshTemplateCandidatesCommand = new AsyncRelayCommand(RefreshTemplateCandidatesAsync,   () => _ssh.IsConnected && !IsBusy);
        TogglePinTemplateCommand         = new RelayCommand(TogglePinTemplate,                     () => !string.IsNullOrWhiteSpace(SelectedTemplate));
        RefreshTaskFilesCommand          = new AsyncRelayCommand(RefreshTaskFilesAsync,             () => _ssh.IsConnected && !IsBusy);
        OpenTaskFileCommand              = new AsyncRelayCommand<TaskFileEntry>(OpenTaskFileAsync);
        GoUpTaskFilesPathCommand         = new AsyncRelayCommand(GoUpTaskFilesPathAsync,            () => _ssh.IsConnected && !IsBusy);
        OpenInConsoleCommand             = new AsyncRelayCommand(OpenInConsoleAsync,                 () => !IsBusy);
        OpenLastSubmitScriptCommand      = new AsyncRelayCommand(OpenLastSubmitScriptAsync,          () => !IsBusy);
        OpenLastSubmitLogCommand         = new AsyncRelayCommand(OpenLastSubmitLogAsync,             () => !IsBusy);
        OpenLastStdoutCommand            = new AsyncRelayCommand(OpenLastStdoutAsync,                () => !IsBusy);
        OpenLastStderrCommand            = new AsyncRelayCommand(OpenLastStderrAsync,                () => !IsBusy);
        OpenLastSubmitWorkDirInConsoleCommand = new AsyncRelayCommand(OpenLastSubmitWorkDirInConsoleAsync, () => !IsBusy);
        RefreshLastSubmitWorkDirFilesCommand = new AsyncRelayCommand(RefreshLastSubmitWorkDirFilesAsync, () => !IsBusy);
        OpenCommandBuilderCommand        = new AsyncRelayCommand(OpenCommandBuilderAsync,           () => !IsBusy);
        SaveAsBlueprintCommand           = new AsyncRelayCommand(SaveAsBlueprintAsync,              () => !IsBusy);
        CreateFromBlueprintCommand       = new AsyncRelayCommand(CreateFromBlueprintAsync,          () => !IsBusy);
        AddTaskUnitCommand               = new RelayCommand(AddTaskUnitInternal);
        RemoveTaskUnitCommand            = new RelayCommand<TaskUnitViewModel>(RemoveTaskUnit, u => u != null && TaskUnits.Count > 1);

        LoadPins();
        Directory.CreateDirectory(LocalDataRoot);

        // Create a single default task unit so the UI is never empty on first run
        EnsureAtLeastOneTaskUnit();
    }

    public void SetOpenInConsoleHandler(Func<string, Task<bool>>? openInConsoleAsync)
    {
        _openInConsoleAsync = openInConsoleAsync;
    }

    // ── Task-unit management ─────────────────────────────────────────────────

    private void EnsureAtLeastOneTaskUnit()
    {
        if (TaskUnits.Count == 0)
        {
            var defaultName = BuildUniqueTaskUnitName();
            var unit = new TaskUnitViewModel(new TaskUnit { TaskName = defaultName, Enabled = true });
            TaskUnits.Add(unit);
            SelectedTaskUnit = unit;
        }
    }

    private void AddTaskUnitInternal()
    {
        var name = BuildUniqueTaskUnitName();
        var unit = new TaskUnitViewModel(new TaskUnit { TaskName = name, Enabled = true });
        TaskUnits.Add(unit);
        SelectedTaskUnit = unit;
    }

    private string BuildUniqueTaskUnitName()
    {
        var baseName = !string.IsNullOrWhiteSpace(TaskId) ? TaskId.Trim() : "task_unit";
        if (!TaskUnits.Any(u => string.Equals(u.TaskName, baseName, StringComparison.OrdinalIgnoreCase)))
            return baseName;

        for (var suffix = 2; suffix <= 10000; suffix++)
        {
            var candidate = $"{baseName} ({suffix})";
            if (!TaskUnits.Any(u => string.Equals(u.TaskName, candidate, StringComparison.OrdinalIgnoreCase)))
                return candidate;
        }

        return $"{baseName} ({DateTime.Now:yyyyMMddHHmmss})";
    }

    private void RemoveTaskUnit(TaskUnitViewModel? unit)
    {
        if (unit == null || TaskUnits.Count <= 1)
        {
            SetStatus("Task.UnitMinimumOne", "WarningTextStyle");
            return;
        }
        var idx = TaskUnits.IndexOf(unit);
        TaskUnits.Remove(unit);
        SelectedTaskUnit = TaskUnits[Math.Min(idx, TaskUnits.Count - 1)];
    }

    private void AddProgram()
    {
        _selectedTaskUnit?.Programs.Add(new ProgramEntryViewModel());
    }

    private void RemoveProgram(ProgramEntryViewModel? p)
    {
        if (p != null) _selectedTaskUnit?.Programs.Remove(p);
    }

    private void AddParamFile()
    {
        _selectedTaskUnit?.ParamFiles.Add(new ParameterFileEntryViewModel());
    }

    private void RemoveParamFile(ParameterFileEntryViewModel? f)
    {
        if (f != null) _selectedTaskUnit?.ParamFiles.Remove(f);
    }

    private void AddCommand()
    {
        _selectedTaskUnit?.Commands.Add(new CommandEntryViewModel());
    }

    private void RemoveCommand(CommandEntryViewModel? c)
    {
        if (c != null) _selectedTaskUnit?.Commands.Remove(c);
    }

    private void AddParam()
    {
        // Create independent instances for both collections to avoid shared-reference side-effects
        var editorEntry = new ParameterEntry();
        Parameters.Add(editorEntry);
        if (_selectedTaskUnit != null)
            _selectedTaskUnit.ExtraParams.Add(new ParameterEntry { Key = editorEntry.Key, Value = editorEntry.Value });
    }

    /// <summary>
    /// Sync scalar editor fields (AppPath, RemoteWorkDir, Parameters…) from the
    /// currently selected task unit so the UI reflects that unit's data.
    /// </summary>
    private void SyncFromSelectedUnit()
    {
        if (_selectedTaskUnit == null) return;

        // App path → first program entry
        AppPath = _selectedTaskUnit.Programs.FirstOrDefault()?.ProgramPath ?? string.Empty;

        // Remote work dir
        if (!string.IsNullOrEmpty(_selectedTaskUnit.RemoteWorkDirectory))
        {
            RemoteWorkDir = _selectedTaskUnit.RemoteWorkDirectory;
            CurrentTaskFilesPath = _selectedTaskUnit.RemoteWorkDirectory;
        }

        // Extra parameters
        Parameters.Clear();
        foreach (var ep in _selectedTaskUnit.ExtraParams)
            Parameters.Add(ep);

        // Template selection → first param file
        var firstParam = _selectedTaskUnit.ParamFiles.FirstOrDefault();
        if (firstParam != null)
            SelectedTemplate = firstParam.FilePath;
    }

    /// <summary>
    /// Write scalar editor field changes back into the selected task unit model
    /// before saving, so both representations stay in sync.
    /// </summary>
    private void SyncToSelectedUnit()
    {
        if (_selectedTaskUnit == null) return;

        // App path → first program entry
        if (!string.IsNullOrWhiteSpace(AppPath))
        {
            if (_selectedTaskUnit.Programs.Count == 0)
                _selectedTaskUnit.Programs.Add(new ProgramEntryViewModel());
            _selectedTaskUnit.Programs[0].ProgramPath = AppPath;
        }

        // Remote work dir
        _selectedTaskUnit.RemoteWorkDirectory = RemoteWorkDir;

        // Extra parameters
        _selectedTaskUnit.ExtraParams.Clear();
        foreach (var p in Parameters)
            _selectedTaskUnit.ExtraParams.Add(p);
    }

    // ── B1: Remote root directory + picker ───────────────────────────────────

    public async void OnConnectionEstablished(string hostOrAddress, string username)
    {
        try
        {
            _connectedHostOrAddress = hostOrAddress?.Trim() ?? string.Empty;
            _connectedUsername = username?.Trim() ?? string.Empty;
            var home = await _ssh.GetHomeDirectoryAsync();
            if (!string.IsNullOrEmpty(home))
            {
                _homeDirectory = NormalizeRemotePath(home);
                RefreshPathDisplays();
            }

            if (!string.IsNullOrEmpty(home) && string.IsNullOrEmpty(RootDirectory))
                RootDirectory = home;

            await RefreshAppCandidatesAsync(CancellationToken.None);
            await RefreshTemplateCandidatesAsync(CancellationToken.None);
            CommandManager.InvalidateRequerySuggested();
        }
        catch (Exception ex)
        {
            SetStatus(string.Format(L("Task.InitAfterConnectFailed"), ex.Message), "ErrorTextStyle", localize: false);
        }
    }

    private async Task BrowseRootDirectoryAsync(CancellationToken ct)
    {
        if (!_ssh.IsConnected)
        {
            SetStatus("Task.RequireConnectionForBrowse", "WarningTextStyle");
            return;
        }

        string homeDir;
        try { homeDir = await _ssh.GetHomeDirectoryAsync(ct); }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[TaskEditorViewModel.BrowseRootDirectoryAsync] {ex.Message}");
            homeDir = RootDirectory;
        }

        if (!string.IsNullOrWhiteSpace(homeDir))
        {
            _homeDirectory = NormalizeRemotePath(homeDir);
            OnPropertyChanged(nameof(RootDirectoryDisplay));
            OnPropertyChanged(nameof(RemoteWorkDirDisplay));
            OnPropertyChanged(nameof(CurrentTaskFilesPathDisplay));
            OnPropertyChanged(nameof(TaskFilesRootPathDisplay));
        }

        if (string.IsNullOrEmpty(homeDir)) homeDir = "/home";

        var vm  = new RemoteDirectoryPickerViewModel(_ssh, homeDir);
        var win = new RemoteDirectoryPickerView { DataContext = vm };

        if (Application.Current.MainWindow is { } mainWin) win.Owner = mainWin;
        await vm.LoadInitialAsync(ct);

        if (win.ShowDialog() == true && vm.ResultPath != null)
            RootDirectory = vm.ResultPath;
    }

    private void TryAutoFillRemoteWorkDir()
    {
        var autoPath = BuildAutoRemoteWorkDir();
        if (string.IsNullOrWhiteSpace(autoPath))
            return;

        var current = NormalizeRemotePath(RemoteWorkDir);
        var previousAuto = NormalizeRemotePath(_lastAutoGeneratedRemoteWorkDir);

        var shouldFollow = string.IsNullOrWhiteSpace(current)
            || _remoteWorkDirFollowsTaskId
            || (!string.IsNullOrWhiteSpace(previousAuto)
                && string.Equals(current, previousAuto, StringComparison.Ordinal));

        _lastAutoGeneratedRemoteWorkDir = NormalizeRemotePath(autoPath);
        if (!shouldFollow)
            return;

        _isAutoUpdatingRemoteWorkDir = true;
        try
        {
            RemoteWorkDir = autoPath;
            CurrentTaskFilesPath = autoPath;
            _remoteWorkDirFollowsTaskId = true;
        }
        finally { _isAutoUpdatingRemoteWorkDir = false; }
    }

    private string BuildAutoRemoteWorkDir()
    {
        if (string.IsNullOrWhiteSpace(RootDirectory) || string.IsNullOrWhiteSpace(TaskId))
            return string.Empty;
        return NormalizeRemotePath($"{RootDirectory.TrimEnd('/')}/{TaskId}");
    }

    private void GenerateNewTaskId()
    {
        TaskId        = $"task_{DateTime.Now:yyyyMMdd_HHmmss}";
        RemoteWorkDir = string.Empty;
        TryAutoFillRemoteWorkDir();
    }

    // ── TaskId directory existence validation ────────────────────────────────

    private void ScheduleTaskIdDirectoryCheck()
    {
        _taskIdValidationCts?.Cancel();
        _taskIdValidationCts?.Dispose();
        _taskIdValidationCts = null;

        _taskIdDirectoryExists = null;
        TaskIdDirectoryStatus  = string.Empty;
        CommandManager.InvalidateRequerySuggested();

        if (!_ssh.IsConnected
            || string.IsNullOrWhiteSpace(RootDirectory)
            || string.IsNullOrWhiteSpace(TaskId))
        {
            return;
        }

        var cts            = new CancellationTokenSource();
        _taskIdValidationCts = cts;
        var capturedTaskId = TaskId;
        var capturedRoot   = RootDirectory;

        _ = Task.Run(async () =>
        {
            try { await Task.Delay(300, cts.Token); }
            catch (OperationCanceledException) { return; }

            if (cts.IsCancellationRequested) return;

            var path = $"{capturedRoot.TrimEnd('/')}/{capturedTaskId}";
            try
            {
                var exists = await _ssh.RemoteDirectoryExistsAsync(path, cts.Token);
                Application.Current.Dispatcher.Invoke(() =>
                {
                    if (cts.IsCancellationRequested) return;
                    _taskIdDirectoryExists = exists;
                    TaskIdDirectoryStatus  = exists
                        ? L("Task.TaskIdDirExists")
                        : L("Task.TaskIdDirNotExists");
                    CommandManager.InvalidateRequerySuggested();
                });
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                Application.Current.Dispatcher.Invoke(() =>
                {
                    if (cts.IsCancellationRequested) return;
                    _taskIdDirectoryExists = null;
                    TaskIdDirectoryStatus  = L("Task.TaskIdDirCheckFailed");
                    System.Diagnostics.Debug.WriteLine($"[TaskIdValidation] {ex.Message}");
                    CommandManager.InvalidateRequerySuggested();
                });
            }
        }, cts.Token);
    }

    // ── App candidates + pinning ─────────────────────────────────────────────

    private async Task RefreshAppCandidatesAsync(CancellationToken ct)
    {
        IsBusy = true;
        try
        {
            var all = new List<string>();
            foreach (var dir in AppSourceDirs)
            {
                try
                {
                    var files = await _ssh.ListFilesAsync(dir, ct);
                    all.AddRange(files.Select(f => $"{dir}/{f}"));
                }
                catch (Exception ex) { System.Diagnostics.Debug.WriteLine($"[TaskEditorViewModel] ListFilesAsync({dir}): {ex.Message}"); }
            }
            RebuildAppDisplayList(all);
        }
        catch (Exception ex) { SetStatus(string.Format(L("Task.RefreshAppCandidatesFailed"), ex.Message), "ErrorTextStyle", localize: false); }
        finally { IsBusy = false; }
    }

    private void RebuildAppDisplayList(IEnumerable<string>? allCandidates = null)
    {
        var existing = allCandidates ?? AppDisplayList.Where(x => !PinnedApps.Contains(x)).ToList();
        AppDisplayList.Clear();
        foreach (var p in PinnedApps)      AppDisplayList.Add(p);
        foreach (var c in existing.Where(c => !PinnedApps.Contains(c))) AppDisplayList.Add(c);
        RebuildFilteredAppList();
    }

    private void RebuildFilteredAppList()
    {
        var filter = _appPath;
        FilteredAppList.Clear();

        if (string.IsNullOrEmpty(filter) || AppDisplayList.Contains(filter))
        {
            foreach (var item in AppDisplayList) FilteredAppList.Add(item);
            return;
        }

        var lower    = filter.ToLowerInvariant();
        var prefix   = AppDisplayList.Where(x => x.ToLowerInvariant().StartsWith(lower)).OrderBy(x => x);
        var contains = AppDisplayList.Where(x =>  x.ToLowerInvariant().Contains(lower)
                                               && !x.ToLowerInvariant().StartsWith(lower)).OrderBy(x => x);
        foreach (var item in prefix.Concat(contains)) FilteredAppList.Add(item);
    }

    private void RebuildFilteredTemplateList()
    {
        var filter = _selectedTemplate;
        FilteredTemplateList.Clear();

        if (string.IsNullOrEmpty(filter) || TemplateDisplayList.Contains(filter))
        {
            foreach (var item in TemplateDisplayList) FilteredTemplateList.Add(item);
            return;
        }

        var lower    = filter.ToLowerInvariant();
        var prefix   = TemplateDisplayList.Where(x => x.ToLowerInvariant().StartsWith(lower)).OrderBy(x => x);
        var contains = TemplateDisplayList.Where(x =>  x.ToLowerInvariant().Contains(lower)
                                                    && !x.ToLowerInvariant().StartsWith(lower)).OrderBy(x => x);
        foreach (var item in prefix.Concat(contains)) FilteredTemplateList.Add(item);
    }

    private void TogglePinApp()
    {
        if (string.IsNullOrWhiteSpace(AppPath)) return;
        if (PinnedApps.Contains(AppPath)) PinnedApps.Remove(AppPath);
        else PinnedApps.Add(AppPath);
        RebuildAppDisplayList();
        SavePins();
    }

    // ── Template candidates + pinning ────────────────────────────────────────

    private async Task RefreshTemplateCandidatesAsync(CancellationToken ct)
    {
        IsBusy = true;
        try
        {
            var files = await _ssh.ListFilesAsync(RemoteTemplateDir, ct);
            RebuildTemplateDisplayList(files);
        }
        catch (Exception ex) { SetStatus(string.Format(L("Task.RefreshTemplateCandidatesFailed"), ex.Message), "ErrorTextStyle", localize: false); }
        finally { IsBusy = false; }
    }

    private void RebuildTemplateDisplayList(IEnumerable<string>? allCandidates = null)
    {
        var existing = allCandidates ?? TemplateDisplayList.Where(x => !PinnedTemplates.Contains(x)).ToList();
        TemplateDisplayList.Clear();
        foreach (var p in PinnedTemplates) TemplateDisplayList.Add(p);
        foreach (var c in existing.Where(c => !PinnedTemplates.Contains(c))) TemplateDisplayList.Add(c);
        RebuildFilteredTemplateList();
    }

    private void TogglePinTemplate()
    {
        if (string.IsNullOrWhiteSpace(SelectedTemplate)) return;
        var t = SelectedTemplate!;
        if (PinnedTemplates.Contains(t)) PinnedTemplates.Remove(t);
        else PinnedTemplates.Add(t);
        RebuildTemplateDisplayList();
        SavePins();
    }

    private void LoadSelectedRemoteTemplate()
    {
        if (string.IsNullOrEmpty(_selectedTemplate)) return;
        _ = Task.Run(async () =>
        {
            try
            {
                var remotePath = $"{RemoteTemplateDir}/{_selectedTemplate}";
                var content    = await _ssh.ReadTextFileAsync(remotePath);
                Application.Current.Dispatcher.Invoke(() => TemplateContent = content);
            }
            catch (Exception ex)
            {
                Application.Current.Dispatcher.Invoke(() =>
                    SetStatus(string.Format(L("Task.LoadTemplateFailed"), ex.Message), "ErrorTextStyle", localize: false));
            }
        });
    }

    // ── Pin persistence ──────────────────────────────────────────────────────

    private sealed record PinsData(List<string> PinnedApps, List<string> PinnedTemplates);

    private void LoadPins()
    {
        try
        {
            if (!File.Exists(PinsFilePath)) return;
            var json = File.ReadAllText(PinsFilePath);
            var data = JsonSerializer.Deserialize<PinsData>(json);
            if (data is null) return;
            foreach (var a in data.PinnedApps)      PinnedApps.Add(a);
            foreach (var t in data.PinnedTemplates) PinnedTemplates.Add(t);
            RebuildAppDisplayList();
            RebuildTemplateDisplayList();
        }
        catch (Exception ex) { System.Diagnostics.Debug.WriteLine($"[TaskEditorViewModel.LoadPins] {ex.Message}"); }
    }

    private void SavePins()
    {
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(PinsFilePath)!);
            var data = new PinsData(PinnedApps.ToList(), PinnedTemplates.ToList());
            File.WriteAllText(PinsFilePath, JsonSerializer.Serialize(data, new JsonSerializerOptions { WriteIndented = true }));
        }
        catch (Exception ex) { System.Diagnostics.Debug.WriteLine($"[TaskEditorViewModel.SavePins] {ex.Message}"); }
    }

    // ── Parameter file save ───────────────────────────────────────────────────

    private async Task SaveParamFileAsync(CancellationToken ct)
    {
        await EnsureHomeDirectoryLoadedAsync(ct);

        if (!ValidateRootAndId() || string.IsNullOrWhiteSpace(SaveAsFileName))
        {
            SetStatus("Task.SaveParamMissingRequired", "WarningTextStyle");
            return;
        }

        if (!_ssh.IsConnected)
        {
            SetStatus("Task.RequireConnectionForSaveParam", "WarningTextStyle");
            return;
        }

        IsBusy = true;
        try
        {
            var remoteParamsDir = $"{RemoteWorkDir.TrimEnd('/')}/params";
            await _ssh.ExecuteAsync($"mkdir -p {EscapeShellArg(remoteParamsDir)}", ct);

            var remoteDest = $"{remoteParamsDir}/{SaveAsFileName}";

            if (await _ssh.RemoteFileExistsAsync(remoteDest, ct))
            {
                var msgText  = Application.Current?.TryFindResource("Task.OverwritePrompt") as string
                               ?? L("Task.OverwritePrompt");
                var msgTitle = Application.Current?.TryFindResource("Task.OverwriteTitle") as string ?? L("Task.OverwriteTitle");
                var result   = MessageBox.Show(
                    string.Format(msgText, remoteDest), msgTitle,
                    MessageBoxButton.OKCancel, MessageBoxImage.Question);
                if (result != MessageBoxResult.OK)
                {
                    SetStatus("Task.SaveCancelled", "InfoTextStyle");
                    return;
                }
            }

            await _ssh.WriteTextFileAsync(remoteDest, TemplateContent, ct);
            LastSavedTime = string.Format(L("Task.SavedAt"), DateTime.Now);
            SetStatus(string.Format(L("Task.ParamFileSaved"), remoteDest), "SuccessTextStyle", localize: false);

            // Register the saved file in the selected unit's param file list
            if (_selectedTaskUnit != null &&
                _selectedTaskUnit.ParamFiles.All(f => f.FilePath != remoteDest))
            {
                _selectedTaskUnit.ParamFiles.Add(
                    new ParameterFileEntryViewModel(new ParameterFileEntry { FilePath = remoteDest, Alias = SaveAsFileName }));
            }
        }
        catch (Exception ex) { SetStatus(string.Format(L("Task.SaveParamFailed"), ex.Message), "ErrorTextStyle", localize: false); }
        finally { IsBusy = false; }
    }

    // ── Task directory file list ──────────────────────────────────────────────

    private async Task RefreshTaskFilesAsync(CancellationToken ct)
    {
        await EnsureHomeDirectoryLoadedAsync(ct);

        if (!_ssh.IsConnected)
        {
            SetStatus("Task.RequireConnection", "WarningTextStyle");
            return;
        }

        var targetPath = NormalizeRemotePath(CurrentTaskFilesPath);
        if (string.IsNullOrWhiteSpace(targetPath))
            targetPath = NormalizeRemotePath(RemoteWorkDir);
        if (string.IsNullOrWhiteSpace(targetPath))
        {
            SetStatus("Task.RequireTaskPath", "WarningTextStyle");
            return;
        }

        IsBusy = true;
        try
        {
            var escapedPath = EscapeShellArg(targetPath);
            var (kindStdOut, _, kindExitCode) = await _ssh.ExecuteAsync(
                $"if [ -d {escapedPath} ]; then echo DIR; " +
                $"elif [ -f {escapedPath} ]; then echo FILE; else echo MISSING; fi", ct);

            var kind = kindStdOut.Trim();
            if (kindExitCode != 0 || kind == "MISSING")
            {
                SetStatus("Task.PathMissing", "ErrorTextStyle");
                return;
            }
            if (kind == "FILE")
            {
                SetStatus("Task.PathIsFile", "ErrorTextStyle");
                return;
            }

            var (stdout, stderr, exitCode) = await _ssh.ExecuteAsync(
                $"ls -1Ap {escapedPath}", ct);

            TaskFiles.Clear();
            CurrentTaskFilesPath = targetPath;

            if (exitCode != 0)
            {
                var errDetail = stderr.Trim();
                SetStatus(string.IsNullOrEmpty(errDetail)
                    ? L("Task.DirReadFailedNoDetail")
                    : string.Format(L("Task.DirReadFailed"), errDetail), "ErrorTextStyle", localize: false);
                return;
            }

            var entries = stdout.Split('\n',
                StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            foreach (var entry in entries)
            {
                var isDirectory = entry.EndsWith("/", StringComparison.Ordinal);
                var name = isDirectory ? entry[..^1] : entry;
                if (name == "." || name == "..") continue;
                var remotePath = BuildRemotePath(targetPath, name);
                TaskFiles.Add(new TaskFileEntry(
                    name,
                    isDirectory,
                    remotePath,
                    CollapseHomePath(remotePath)));
            }

            SetStatus(TaskFiles.Count == 0
                ? L("Task.DirEmpty")
                : string.Format(L("Task.DirLoadedCount"), TaskFiles.Count), "InfoTextStyle", localize: false);
        }
        catch (Exception ex) { SetStatus(string.Format(L("Task.RefreshFilesFailed"), ex.Message), "ErrorTextStyle", localize: false); }
        finally { IsBusy = false; }
    }

    private async Task GoUpTaskFilesPathAsync(CancellationToken ct)
    {
        var current = NormalizeRemotePath(CurrentTaskFilesPath);
        if (string.IsNullOrWhiteSpace(current))
        {
            SetStatus("Task.GoUpPathEmpty", "WarningTextStyle");
            return;
        }

        var slashIndex = current.LastIndexOf('/');
        var up = current == "/" || slashIndex <= 0 ? "/" : current[..slashIndex];
        CurrentTaskFilesPath = string.IsNullOrWhiteSpace(up) ? "/" : up;
        await RefreshTaskFilesAsync(ct);
    }

    private async Task OpenTaskFileAsync(TaskFileEntry? fileEntry, CancellationToken ct)
    {
        if (fileEntry == null) return;
        if (!_ssh.IsConnected) { SetStatus("Task.RequireConnection", "WarningTextStyle"); return; }

        if (fileEntry.IsDirectory)
        {
            CurrentTaskFilesPath = fileEntry.RemotePath;
            await RefreshTaskFilesAsync(ct);
            return;
        }

        var remotePath = fileEntry.RemotePath;
        var vm  = new RemoteFileEditorViewModel(_ssh, remotePath, _homeDirectory);
        var win = new RemoteFileEditorView { DataContext = vm };

        if (Application.Current.MainWindow is { } mainWin) win.Owner = mainWin;
        await vm.LoadAsync(ct);
        if (vm.IsBinaryFile)
        {
            StatusMessage = vm.StatusMessage;
            StatusStyleKey = vm.StatusStyleKey;
            return;
        }

        win.ShowDialog();
    }

    private async Task OpenInConsoleAsync(CancellationToken ct)
    {
        await EnsureHomeDirectoryLoadedAsync(ct);

        if (!_ssh.IsConnected)
        {
            SetStatus("Task.RequireConnection", "WarningTextStyle");
            return;
        }

        var preferredDirectory = NormalizeRemotePath(ExpandHomePath(CurrentTaskFilesPath));
        var fallbackDirectory = NormalizeRemotePath(ExpandHomePath(RemoteWorkDir));
        var targetDirectory = string.IsNullOrWhiteSpace(preferredDirectory)
            ? fallbackDirectory
            : preferredDirectory;

        if (string.IsNullOrWhiteSpace(targetDirectory))
        {
            SetStatus("Task.OpenInTerminalMissingDir", "WarningTextStyle");
            return;
        }

        if (_openInConsoleAsync == null)
        {
            SetStatus("Task.OpenInTerminalUnavailable", "WarningTextStyle");
            return;
        }

        var opened = await _openInConsoleAsync(targetDirectory);
        if (opened)
            SetStatus(string.Format(L("Task.OpenInTerminalSuccess"), CollapseHomePath(targetDirectory)), "SuccessTextStyle", localize: false);
        else
            SetStatus(string.Format(L("Task.OpenInTerminalFailed"), CollapseHomePath(targetDirectory)), "WarningTextStyle", localize: false);
    }

    // ── Command Builder dialog ────────────────────────────────────────────────

    private async Task OpenCommandBuilderAsync(CancellationToken ct)
    {
        EnsureAtLeastOneTaskUnit();
        var unit = _selectedTaskUnit!;

        var dlgVm = new CommandBuilderViewModel(
            _ssh,
            taskId:         TaskId,
            remoteWorkDir:  RemoteWorkDir,
            initialCommands: unit.Commands.Select(c => c.ToModel()),
            initialSbatch:  unit.SbatchTemplate);

        var win = new CommandBuilderView { DataContext = dlgVm };
        if (Application.Current.MainWindow is { } mainWin) win.Owner = mainWin;

        if (_ssh.IsConnected)
            await dlgVm.LoadInitialAsync(ct);

        if (win.ShowDialog() == true && dlgVm.Confirmed)
        {
            // Apply commands back to the active task unit
            unit.Commands.Clear();
            foreach (var ce in dlgVm.GetResultCommands())
                unit.Commands.Add(new CommandEntryViewModel(ce));

            // Sync first command's program path back into Programs list for legacy submit logic
            var firstProg = dlgVm.GetResultCommands()
                .Where(c => !string.IsNullOrWhiteSpace(c.ProgramPath))
                .FirstOrDefault()?.ProgramPath ?? string.Empty;
            unit.Programs.Clear();
            if (!string.IsNullOrWhiteSpace(firstProg))
                unit.Programs.Add(new ProgramEntryViewModel(new Core.Models.ProgramEntry { ProgramPath = firstProg, Order = 0 }));
            AppPath = firstProg;

            // Persist the user-edited sbatch content on the unit
            unit.SbatchTemplate = dlgVm.GetResultSbatch();

            SetStatus("Task.CommandUpdated", "SuccessTextStyle");
            CommandManager.InvalidateRequerySuggested();
        }
    }

    // ── Task blueprint ───────────────────────────────────────────────────────

    private async Task SaveAsBlueprintAsync(CancellationToken ct)
    {
        var scope = GetCurrentBlueprintScope();
        if (scope == null)
        {
            SetStatus("Task.RequireConnection", "WarningTextStyle");
            return;
        }

        EnsureAtLeastOneTaskUnit();
        SyncToSelectedUnit();

        var dialogVm = new TaskBlueprintSaveViewModel(initialName: TaskId);
        var dialog = new TaskBlueprintSaveView { DataContext = dialogVm };
        if (Application.Current.MainWindow is { } mainWin) dialog.Owner = mainWin;

        if (dialog.ShowDialog() != true || !dialogVm.Confirmed)
            return;

        if (TaskUnits.All(u => u.Commands.Count == 0 && u.Programs.Count == 0))
        {
            MessageBox.Show(
                L("Task.BlueprintIncompleteWarning"),
                L("Task.BlueprintSaveTitle"),
                MessageBoxButton.OK,
                MessageBoxImage.Information);
        }

        var overwrite = false;
        if (await _blueprints.ExistsByNameAsync(dialogVm.BlueprintName, scope, ct))
        {
            var confirm = MessageBox.Show(
                string.Format(L("Task.BlueprintOverwriteConfirm"), dialogVm.BlueprintName),
                L("Task.BlueprintOverwriteTitle"),
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);
            if (confirm != MessageBoxResult.Yes)
            {
                SetStatus("Task.SaveCancelled", "InfoTextStyle");
                return;
            }

            overwrite = true;
        }

        try
        {
            var blueprint = BuildBlueprintRecord(dialogVm.BlueprintName, dialogVm.BlueprintDescription, scope);
            await _blueprints.SaveAsync(blueprint, scope, overwriteByName: overwrite, ct);
            SetStatus(string.Format(L("Task.BlueprintSaveSucceeded"), blueprint.Name), "SuccessTextStyle", localize: false);
        }
        catch (Exception ex)
        {
            SetStatus(string.Format(L("Task.BlueprintSaveFailed"), ex.Message), "ErrorTextStyle", localize: false);
        }
    }

    private async Task CreateFromBlueprintAsync(CancellationToken ct)
    {
        var scope = GetCurrentBlueprintScope();
        if (scope == null)
        {
            SetStatus("Task.RequireConnection", "WarningTextStyle");
            return;
        }

        var dialogVm = new TaskBlueprintCreateViewModel(_blueprints, scope)
        {
            NewTaskId = string.IsNullOrWhiteSpace(TaskId)
                ? $"task_{DateTime.UtcNow:yyyyMMdd_HHmmss_fff}"
                : $"{TaskId}_new",
        };
        await dialogVm.LoadAsync(ct);

        var dialog = new TaskBlueprintCreateView { DataContext = dialogVm };
        if (Application.Current.MainWindow is { } mainWin) dialog.Owner = mainWin;

        if (dialog.ShowDialog() != true || !dialogVm.Confirmed || dialogVm.SelectedBlueprintRecord == null)
            return;

        try
        {
            var warnings = ApplyBlueprintToEditor(dialogVm.SelectedBlueprintRecord, dialogVm.NewTaskId.Trim());
            var successMessage = string.Format(L("Task.BlueprintCreateSucceeded"), dialogVm.NewTaskId.Trim());
            if (warnings.Count == 0)
            {
                SetStatus(successMessage, "SuccessTextStyle", localize: false);
            }
            else
            {
                SetStatus($"{successMessage}\n{string.Join("\n", warnings)}", "WarningTextStyle", localize: false);
                MessageBox.Show(
                    string.Join("\n", warnings),
                    L("Task.BlueprintApplyNoticeTitle"),
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }
        }
        catch (Exception ex)
        {
            SetStatus(string.Format(L("Task.BlueprintCreateFailed"), ex.Message), "ErrorTextStyle", localize: false);
        }
    }

    private TaskBlueprintRecord BuildBlueprintRecord(string name, string description, TaskBlueprintScope scope)
    {
        var workspace = BuildWorkspace();

        return new TaskBlueprintRecord
        {
            BlueprintId = Guid.NewGuid().ToString("N"),
            Name = name.Trim(),
            Description = description.Trim(),
            Version = TaskBlueprintRecord.CurrentVersion,
            SourceTaskId = TaskId,
            RootDirectory = RootDirectory,
            RemoteWorkDirectory = RemoteWorkDir,
            ActiveTaskUnitName = SelectedTaskUnit?.TaskName,
            ScopeHostOrAddress = scope.HostOrAddress,
            ScopeUsername = scope.Username,
            ScopeKey = TaskBlueprintScope.BuildScopeKey(scope.HostOrAddress, scope.Username),
            TaskUnits = workspace.Tasks.Select(CloneTaskUnit).ToList(),
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
        };
    }

    private TaskBlueprintScope? GetCurrentBlueprintScope()
    {
        if (string.IsNullOrWhiteSpace(_connectedHostOrAddress) || string.IsNullOrWhiteSpace(_connectedUsername))
            return null;

        return new TaskBlueprintScope
        {
            HostOrAddress = _connectedHostOrAddress,
            Username = _connectedUsername,
        };
    }

    private List<string> ApplyBlueprintToEditor(TaskBlueprintRecord blueprint, string newTaskId)
    {
        var warnings = new HashSet<string>(StringComparer.Ordinal);

        if (!string.IsNullOrWhiteSpace(blueprint.RootDirectory))
            RootDirectory = blueprint.RootDirectory.Trim();

        var oldTaskId = blueprint.SourceTaskId?.Trim() ?? string.Empty;
        TaskId = newTaskId;

        var blueprintRoot = blueprint.RootDirectory?.Trim();
        var normalizedLegacyAutoDir = string.IsNullOrWhiteSpace(blueprintRoot) || string.IsNullOrWhiteSpace(oldTaskId)
            ? string.Empty
            : NormalizeRemotePath($"{blueprintRoot.TrimEnd('/')}/{oldTaskId}");

        var sourceWorkspaceWorkDir = NormalizeRemotePath(blueprint.RemoteWorkDirectory);
        var normalizedNewAutoDir = NormalizeRemotePath(BuildAutoRemoteWorkDir());
        var fallbackWorkDir = !string.IsNullOrWhiteSpace(normalizedNewAutoDir)
            ? normalizedNewAutoDir
            : sourceWorkspaceWorkDir;
        var sourceWorkspaceIsAuto = IsAutoGeneratedWorkDir(sourceWorkspaceWorkDir, normalizedLegacyAutoDir);

        TaskUnits.Clear();
        var sourceUnits = blueprint.TaskUnits.Count > 0
            ? blueprint.TaskUnits
            : new List<TaskUnit> { new() { TaskName = newTaskId, Enabled = true } };

        foreach (var source in sourceUnits)
        {
            var adapted = CloneTaskUnit(source);
            adapted.SlurmJobId = null;

            AdaptTaskUnitForNewTask(
                adapted,
                oldTaskId,
                newTaskId,
                sourceWorkspaceWorkDir,
                sourceWorkspaceIsAuto,
                normalizedLegacyAutoDir,
                fallbackWorkDir,
                warnings);

            if (string.IsNullOrWhiteSpace(adapted.TaskName) ||
                (!string.IsNullOrWhiteSpace(oldTaskId)
                    && string.Equals(adapted.TaskName, oldTaskId, StringComparison.OrdinalIgnoreCase)))
            {
                adapted.TaskName = newTaskId;
            }

            TaskUnits.Add(new TaskUnitViewModel(adapted));
        }

        EnsureAtLeastOneTaskUnit();
        SelectedTaskUnit = TaskUnits.FirstOrDefault(u =>
            string.Equals(u.TaskName, blueprint.ActiveTaskUnitName, StringComparison.OrdinalIgnoreCase))
            ?? TaskUnits[0];

        SyncFromSelectedUnit();
        if (string.IsNullOrWhiteSpace(RemoteWorkDir) && !string.IsNullOrWhiteSpace(fallbackWorkDir))
        {
            RemoteWorkDir = fallbackWorkDir;
            CurrentTaskFilesPath = fallbackWorkDir;
        }

        LastJobId = null;
        LastSavedTime = string.Empty;

        return warnings.ToList();
    }

    private void AdaptTaskUnitForNewTask(
        TaskUnit unit,
        string oldTaskId,
        string newTaskId,
        string sourceWorkspaceWorkDir,
        bool sourceWorkspaceIsAuto,
        string normalizedLegacyAutoDir,
        string fallbackWorkDir,
        HashSet<string> warnings)
    {
        var sourceUnitWorkDir = NormalizeRemotePath(unit.RemoteWorkDirectory);
        if (string.IsNullOrWhiteSpace(sourceUnitWorkDir))
        {
            if (!string.IsNullOrWhiteSpace(sourceWorkspaceWorkDir))
            {
                if (sourceWorkspaceIsAuto)
                {
                    unit.RemoteWorkDirectory = fallbackWorkDir;
                }
                else
                {
                    SetRemoteWorkDirectoryWithReviewWarning(unit, sourceWorkspaceWorkDir, warnings);
                }
            }
            else
            {
                unit.RemoteWorkDirectory = fallbackWorkDir;
            }
        }
        else if (IsAutoGeneratedWorkDir(sourceUnitWorkDir, normalizedLegacyAutoDir))
        {
            unit.RemoteWorkDirectory = fallbackWorkDir;
        }
        else
        {
            SetRemoteWorkDirectoryWithReviewWarning(unit, sourceUnitWorkDir, warnings);
        }

        unit.SbatchTemplate = AdaptSbatchTemplate(unit.SbatchTemplate, oldTaskId, newTaskId, warnings);

        foreach (var p in unit.ParameterFiles)
            p.FilePath = AdaptParameterPath(p.FilePath, oldTaskId, unit.RemoteWorkDirectory ?? fallbackWorkDir, warnings);

        foreach (var c in unit.CommandEntries)
        {
            c.ParameterFiles = c.ParameterFiles
                .Select(path => AdaptParameterPath(path, oldTaskId, unit.RemoteWorkDirectory ?? fallbackWorkDir, warnings))
                .ToList();
        }
    }

    private void SetRemoteWorkDirectoryWithReviewWarning(TaskUnit unit, string workDir, HashSet<string> warnings)
    {
        unit.RemoteWorkDirectory = workDir;
        warnings.Add(L("Task.BlueprintRemoteWorkDirNeedsReview"));
    }

    private string AdaptSbatchTemplate(
        string? template,
        string oldTaskId,
        string newTaskId,
        HashSet<string> warnings)
    {
        if (string.IsNullOrWhiteSpace(template))
            return template ?? string.Empty;

        var lines = template.Replace("\r\n", "\n").Split('\n').ToList();
        var replacedOldTaskId = false;
        var hasJobName = false;

        for (var i = 0; i < lines.Count; i++)
        {
            var line = lines[i];
            var trimmed = line.TrimStart();
            if (trimmed.StartsWith("#SBATCH --job-name", StringComparison.OrdinalIgnoreCase))
            {
                var prefix = line[..(line.Length - trimmed.Length)];
                line = $"{prefix}#SBATCH --job-name={newTaskId}";
                hasJobName = true;
            }

            if (!string.IsNullOrWhiteSpace(oldTaskId)
                && !string.Equals(oldTaskId, newTaskId, StringComparison.Ordinal)
                && TryReplaceTaskIdLiteral(line, oldTaskId, newTaskId, out var replacedLine))
            {
                line = replacedLine;
                replacedOldTaskId = true;
            }

            lines[i] = line;
        }

        if (!hasJobName)
        {
            var insertAt = lines.Count > 0 && lines[0].StartsWith("#!", StringComparison.Ordinal) ? 1 : 0;
            lines.Insert(insertAt, $"#SBATCH --job-name={newTaskId}");
        }

        if (!string.IsNullOrWhiteSpace(oldTaskId) && !replacedOldTaskId)
            warnings.Add(L("Task.BlueprintSbatchNeedsReview"));

        return string.Join('\n', lines);
    }

    private string AdaptParameterPath(string? path, string oldTaskId, string unitWorkDir, HashSet<string> warnings)
    {
        if (string.IsNullOrWhiteSpace(path))
            return string.Empty;

        var normalized = path.Trim().Replace('\\', '/');
        if (normalized.StartsWith("/", StringComparison.Ordinal))
            return normalized;

        var normalizedWorkDir = NormalizeRemotePath(unitWorkDir);
        if (string.IsNullOrWhiteSpace(normalizedWorkDir))
        {
            warnings.Add(L("Task.BlueprintParameterPathNeedsReview"));
            return normalized;
        }

        var mapped = $"{normalizedWorkDir.TrimEnd('/')}/params/{normalized.TrimStart('/')}";
        if (!string.IsNullOrWhiteSpace(oldTaskId)
            && ContainsTaskIdLiteral(normalized, oldTaskId))
        {
            warnings.Add(L("Task.BlueprintContainsOldTaskIdPathWarning"));
        }
        return mapped;
    }

    private static bool TryReplaceTaskIdLiteral(string input, string oldTaskId, string newTaskId, out string replaced)
    {
        replaced = input;
        if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(oldTaskId))
            return false;

        var pattern = BuildTaskIdLiteralPattern(oldTaskId);
        var changed = false;
        replaced = Regex.Replace(input, pattern, _ =>
        {
            changed = true;
            return newTaskId;
        });

        return changed;
    }

    private static bool ContainsTaskIdLiteral(string input, string taskId)
    {
        if (string.IsNullOrWhiteSpace(input) || string.IsNullOrWhiteSpace(taskId))
            return false;

        return Regex.IsMatch(input, BuildTaskIdLiteralPattern(taskId));
    }

    private static string BuildTaskIdLiteralPattern(string taskId)
        => $@"(?<![A-Za-z0-9_-]){Regex.Escape(taskId)}(?![A-Za-z0-9_-])";

    private static bool IsAutoGeneratedWorkDir(string candidate, string normalizedLegacyAutoDir)
    {
        if (string.IsNullOrWhiteSpace(candidate) || string.IsNullOrWhiteSpace(normalizedLegacyAutoDir))
            return false;

        return string.Equals(
            NormalizeRemotePath(candidate),
            NormalizeRemotePath(normalizedLegacyAutoDir),
            StringComparison.OrdinalIgnoreCase);
    }

    private static TaskUnit CloneTaskUnit(TaskUnit source) => new()
    {
        TaskName = source.TaskName,
        Enabled = source.Enabled,
        RemoteWorkDirectory = source.RemoteWorkDirectory,
        SlurmJobId = source.SlurmJobId,
        SbatchTemplate = source.SbatchTemplate,
        ProgramEntries = source.ProgramEntries.Select(p => new ProgramEntry
        {
            ProgramPath = p.ProgramPath,
            ArgsTemplate = p.ArgsTemplate,
            Order = p.Order,
        }).ToList(),
        ParameterFiles = source.ParameterFiles.Select(f => new ParameterFileEntry
        {
            FilePath = f.FilePath,
            Alias = f.Alias,
            IsPinned = f.IsPinned,
        }).ToList(),
        CommandEntries = source.CommandEntries.Select(c => new CommandEntry
        {
            CommandLine = c.CommandLine,
            Description = c.Description,
            Order = c.Order,
            ProgramPath = c.ProgramPath,
            ParameterFiles = c.ParameterFiles.ToList(),
            ExtraArgs = c.ExtraArgs.ToList(),
            MpirunPath = c.MpirunPath,
        }).ToList(),
        ExtraParameters = new Dictionary<string, string>(source.ExtraParameters),
    };

    // ── Persistence (workspace + legacy) ────────────────────────────────────

    private string GetLocalTaskDir() => Path.Combine(LocalDataRoot, TaskId);

    private async Task SaveTaskAsync(CancellationToken ct)
    {
        if (!ValidateRootAndId()) return;
        IsBusy = true;
        SetStatus("Task.Saving", "InfoTextStyle");
        try
        {
            Directory.CreateDirectory(GetLocalTaskDir());
            SyncToSelectedUnit();

            var workspace = BuildWorkspace();
            await _storage.SaveWorkspaceAsync(workspace, ct);

            // Also persist legacy task.json for tooling that reads only that
            await _storage.SaveAsync(BuildTaskRecord(), ct);

            SetStatus(string.Format(L("Task.SavedPath"), GetLocalTaskDir()), "SuccessTextStyle", localize: false);
            LastSavedTime = string.Format(L("Task.LastSavedAt"), DateTime.Now);
        }
        catch (Exception ex) { SetStatus(string.Format(L("Task.SaveFailed"), ex.Message), "ErrorTextStyle", localize: false); }
        finally { IsBusy = false; }
    }

    private async Task LoadTaskAsync(CancellationToken ct)
    {
        if (!ValidateRootAndId()) return;
        IsBusy = true;
        SetStatus("Task.Loading", "InfoTextStyle");
        try
        {
            var workspace = await _storage.LoadWorkspaceAsync(LocalDataRoot, TaskId, ct);
            if (workspace == null)
            {
                // Try legacy path
                var record = await _storage.LoadAsync(LocalDataRoot, TaskId, ct);
                if (record == null) { SetStatus("Task.LoadNotFound", "WarningTextStyle"); return; }
                ApplyTaskRecord(record);
                SetStatus(string.Format(L("Task.LoadedLegacy"), TaskId), "SuccessTextStyle", localize: false);
                return;
            }

            ApplyWorkspace(workspace);
            SetStatus(string.Format(L("Task.WorkspaceLoaded"), TaskId, workspace.Tasks.Count), "SuccessTextStyle", localize: false);
        }
        catch (Exception ex) { SetStatus(string.Format(L("Task.LoadFailed"), ex.Message), "ErrorTextStyle", localize: false); }
        finally { IsBusy = false; }
    }

    private void ApplyWorkspace(TaskWorkspace w)
    {
        TaskUnits.Clear();

        if (w.Tasks.Count == 0)
        {
            // No units in workspace — create a fresh default
            EnsureAtLeastOneTaskUnit();
            return;
        }

        if (w.Tasks.Count == 1)
        {
            // Exactly one unit — the happy path
            TaskUnits.Add(new TaskUnitViewModel(w.Tasks[0]));
            SelectedTaskUnit = TaskUnits[0];
            return;
        }

        // Legacy multi-unit workspace: prompt the user to pick one active unit.
        // All units are loaded internally but only the chosen one is used for editing/submitting.
        foreach (var unit in w.Tasks)
            TaskUnits.Add(new TaskUnitViewModel(unit));

        var names   = TaskUnits.Select((u, i) => $"{i + 1}. {u.TaskName}").ToArray();
        var prompt  = Application.Current?.TryFindResource("Task.MultiUnitPrompt") as string
                      ?? L("Task.MultiUnitPrompt");
        SetStatus(string.Format(prompt, string.Join("\n", names)), "InfoTextStyle", localize: false);

        // Default: use the first unit
        SelectedTaskUnit = TaskUnits[0];
    }

    private TaskWorkspace BuildWorkspace() => new()
    {
        TaskId   = TaskId,
        RootPath = LocalDataRoot,
        Tasks    = TaskUnits.Select(u => u.ToModel()).ToList(),
    };

    // ── sbatch submit ────────────────────────────────────────────────────────

    private async Task SubmitJobAsync(CancellationToken ct)
    {
        if (!ValidateSubmitRequirements()) return;

        if (_selectedTaskUnit == null)
        {
            SetStatus("Task.NoActiveUnit", "WarningTextStyle");
            return;
        }

        IsBusy = true;
        SetStatus("Task.SubmitPreparing", "InfoTextStyle");
        try
        {
            PrepareLastSubmitPaths(_selectedTaskUnit);
            var jobId = await SubmitUnitAsync(_selectedTaskUnit, ct);
            LastJobId = jobId;
            LastSubmitStatusStyleKey = "SuccessTextStyle";
            LastSubmitStatusMessage = string.Format(L("Task.DiagnosticSubmitSuccess"), jobId);
            LastSubmitStageLabel = L("Task.SubmitStageSbatchSubmit");
            LastSubmitNextSteps = L("Task.SubmitAdviceSuccess");
            SetStatus(string.Format(L("Task.SubmitSucceeded"), jobId), "SuccessTextStyle", localize: false);
        }
        catch (SubmitStageException ex)
        {
            LastSubmitStatusStyleKey = "ErrorTextStyle";
            LastSubmitStageLabel = StageToLabel(ex.Stage);
            LastSubmitStatusMessage = string.Format(
                L("Task.SubmitFailedWithStage"),
                LastSubmitStageLabel,
                ex.Message);
            LastSubmitNextSteps = BuildSubmitNextSteps(ex.Stage);
            SetStatus(LastSubmitStatusMessage, "ErrorTextStyle", localize: false);
        }
        catch (Exception ex)
        {
            LastSubmitStatusStyleKey = "ErrorTextStyle";
            LastSubmitStageLabel = StageToLabel(SubmitFailureStage.Unknown);
            LastSubmitStatusMessage = string.Format(
                L("Task.SubmitFailedWithStage"),
                LastSubmitStageLabel,
                ex.Message);
            LastSubmitNextSteps = BuildSubmitNextSteps(SubmitFailureStage.Unknown);
            SetStatus(LastSubmitStatusMessage, "ErrorTextStyle", localize: false);
        }
        finally { IsBusy = false; }

        OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
        CommandManager.InvalidateRequerySuggested();
    }

    private async Task<long> SubmitUnitAsync(TaskUnitViewModel unit, CancellationToken ct)
    {
        var workDir = ResolveWorkDirForSubmit(unit);
        if (string.IsNullOrWhiteSpace(workDir))
            throw new SubmitStageException(SubmitFailureStage.LocalContextMissing, L("Task.InvalidRemoteWorkDir"));

        var appPath = unit.Programs.FirstOrDefault()?.ProgramPath ?? AppPath;
        if (string.IsNullOrWhiteSpace(appPath))
            throw new SubmitStageException(SubmitFailureStage.LocalContextMissing, L("Task.RequireAppPath"));

        if (!_ssh.IsConnected)
            throw new SubmitStageException(SubmitFailureStage.SshConnectionFailed, L("Task.RequireConnection"));

        var paramFile = GetParameterFilePath(unit, workDir);
        var normalizedWorkDir = NormalizeRemotePath(workDir);
        var stdoutPath = $"{normalizedWorkDir.TrimEnd('/')}/logs/job.out";
        var stderrPath = $"{normalizedWorkDir.TrimEnd('/')}/logs/job.err";

        var parameters = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["JOB_NAME"]    = !string.IsNullOrEmpty(unit.TaskName) ? unit.TaskName : TaskId,
            ["WORK_DIR"]    = normalizedWorkDir,
            ["APP_PATH"]    = appPath,
            ["PARAM_FILE"]  = paramFile,
            ["STDOUT_FILE"] = stdoutPath,
            ["STDERR_FILE"] = stderrPath,
        };
        foreach (var (k, v) in unit.ToModel().ExtraParameters)
            parameters[k] = v;

        var template  = !string.IsNullOrEmpty(unit.SbatchTemplate) ? unit.SbatchTemplate : SbatchTemplate;
        string rendered;
        try
        {
            rendered = new SbatchTemplateRenderer(template).Render(parameters);
        }
        catch (Exception ex)
        {
            throw new SubmitStageException(SubmitFailureStage.ScriptRenderFailed, ex.Message, ex);
        }

        var localTaskDir = GetLocalTaskDir();
        var unitNameForPath = ResolveUnitNameForPath(unit);
        var scriptsDir   = Path.Combine(localTaskDir, unitNameForPath, "scripts");
        var localLogsDir = Path.Combine(localTaskDir, unitNameForPath, "logs");
        try
        {
            Directory.CreateDirectory(scriptsDir);
            Directory.CreateDirectory(localLogsDir);
        }
        catch (Exception ex)
        {
            throw new SubmitStageException(SubmitFailureStage.LocalContextMissing, ex.Message, ex);
        }

        var localScript = Path.Combine(scriptsDir, "submit.sbatch");
        try
        {
            await File.WriteAllTextAsync(localScript, rendered, ct);
        }
        catch (Exception ex)
        {
            throw new SubmitStageException(SubmitFailureStage.LocalContextMissing, ex.Message, ex);
        }

        SetStatus(string.Format(L("Task.SubmittingUnit"), unit.TaskName), "InfoTextStyle", localize: false);
        try
        {
            var escapedWorkDir = EscapeShellArg(normalizedWorkDir);
            var (_, dirErr, dirExit) = await _ssh.ExecuteAsync($"mkdir -p {escapedWorkDir}/logs", ct);
            if (dirExit != 0)
            {
                var detail = string.IsNullOrWhiteSpace(dirErr) ? L("Task.RemoteWorkDirPrepareFailedNoDetail") : dirErr.Trim();
                throw new SubmitStageException(SubmitFailureStage.RemoteWorkDirFailed, detail);
            }
        }
        catch (Exception ex)
        {
            throw new SubmitStageException(SubmitFailureStage.RemoteWorkDirFailed, ex.Message, ex);
        }

        if (!string.IsNullOrWhiteSpace(paramFile))
        {
            try
            {
                if (!await _ssh.RemoteFileExistsAsync(paramFile, ct))
                    throw new SubmitStageException(SubmitFailureStage.ParameterPathFailed, string.Format(L("Task.ParameterFileMissing"), paramFile));
            }
            catch (Exception ex)
            {
                throw new SubmitStageException(SubmitFailureStage.ParameterPathFailed, ex.Message, ex);
            }
        }

        long jobId;
        try
        {
            jobId = await _slurm.SubmitSbatchAsync(localScript, normalizedWorkDir, ct);
        }
        catch (Exception ex) when (IsConnectionRelated(ex))
        {
            throw new SubmitStageException(SubmitFailureStage.SshConnectionFailed, ex.Message, ex);
        }
        catch (Exception ex)
        {
            throw new SubmitStageException(SubmitFailureStage.SbatchSubmitFailed, ex.Message, ex);
        }

        unit.SlurmJobId = jobId;

        var localSubmitLog = Path.Combine(localLogsDir, "submit.log");
        await File.WriteAllTextAsync(
            localSubmitLog,
            $"Submitted at {DateTime.UtcNow:u}\nJob ID: {jobId}\n",
            ct);

        LastSubmitUnitName = unit.TaskName;
        LastSubmitRemoteWorkDir = normalizedWorkDir;
        LastSubmitRemoteStdoutPath = stdoutPath;
        LastSubmitRemoteStderrPath = stderrPath;
        LastSubmitLocalScriptPath = localScript;
        LastSubmitLocalSubmitLogPath = localSubmitLog;
        OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
        OnPropertyChanged(nameof(LastSubmitRemoteWorkDirDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStdoutPathDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStderrPathDisplay));

        return jobId;
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Resolves the remote parameter file path for a task unit submission.
    /// Priority: unit's first ParameterFile → global SelectedTemplate → empty.
    /// </summary>
    private string GetParameterFilePath(TaskUnitViewModel unit, string workDir)
    {
        var firstParam = unit.ParamFiles.FirstOrDefault()?.FilePath;
        if (!string.IsNullOrEmpty(firstParam))
            return ResolveParameterPath(firstParam, workDir);

        if (!string.IsNullOrEmpty(SelectedTemplate))
            return ResolveParameterPath(SelectedTemplate, workDir);

        return string.Empty;
    }

    private bool CanSubmit() =>
        !IsBusy
        && _ssh.IsConnected
        && !string.IsNullOrWhiteSpace(RootDirectory)
        && !string.IsNullOrWhiteSpace(TaskId)
        && !string.IsNullOrWhiteSpace(ResolveWorkDirForSubmit(_selectedTaskUnit))
        && (!string.IsNullOrWhiteSpace(AppPath)
            || (_selectedTaskUnit?.Programs.Any(p => !string.IsNullOrWhiteSpace(p.ProgramPath)) == true));

    private bool ValidateRootAndId()
    {
        if (string.IsNullOrWhiteSpace(RootDirectory))
        {
            SetStatus("Task.RequireRootDirectory", "WarningTextStyle");
            LastSubmitStatusStyleKey = "WarningTextStyle";
            LastSubmitStatusMessage = L("Task.RequireRootDirectory");
            LastSubmitStageLabel = StageToLabel(SubmitFailureStage.LocalContextMissing);
            LastSubmitNextSteps = BuildSubmitNextSteps(SubmitFailureStage.LocalContextMissing);
            OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
            return false;
        }

        if (string.IsNullOrWhiteSpace(TaskId))
        {
            SetStatus("Task.RequireTaskId", "WarningTextStyle");
            LastSubmitStatusStyleKey = "WarningTextStyle";
            LastSubmitStatusMessage = L("Task.RequireTaskId");
            LastSubmitStageLabel = StageToLabel(SubmitFailureStage.LocalContextMissing);
            LastSubmitNextSteps = BuildSubmitNextSteps(SubmitFailureStage.LocalContextMissing);
            OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
            return false;
        }
        return true;
    }

    private bool ValidateSubmitRequirements()
    {
        if (!_ssh.IsConnected)
        {
            SetStatus("Task.SubmitValidationNeedConnection", "WarningTextStyle");
            LastSubmitStatusStyleKey = "WarningTextStyle";
            LastSubmitStatusMessage = L("Task.SubmitValidationNeedConnection");
            LastSubmitStageLabel = StageToLabel(SubmitFailureStage.SshConnectionFailed);
            LastSubmitNextSteps = BuildSubmitNextSteps(SubmitFailureStage.SshConnectionFailed);
            OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
            return false;
        }
        if (!ValidateRootAndId()) return false;
        var workDir = ResolveWorkDirForSubmit(_selectedTaskUnit);
        if (string.IsNullOrWhiteSpace(workDir))
        {
            SetStatus("Task.SubmitValidationNeedRemoteWorkDir", "WarningTextStyle");
            LastSubmitStatusStyleKey = "WarningTextStyle";
            LastSubmitStatusMessage = L("Task.SubmitValidationNeedRemoteWorkDir");
            LastSubmitStageLabel = StageToLabel(SubmitFailureStage.LocalContextMissing);
            LastSubmitNextSteps = BuildSubmitNextSteps(SubmitFailureStage.LocalContextMissing);
            OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
            return false;
        }

        var hasApp = !string.IsNullOrWhiteSpace(AppPath)
            || (_selectedTaskUnit?.Programs.Any(p => !string.IsNullOrWhiteSpace(p.ProgramPath)) == true);
        if (!hasApp)
        {
            SetStatus("Task.SubmitValidationNeedAppPath", "WarningTextStyle");
            LastSubmitStatusStyleKey = "WarningTextStyle";
            LastSubmitStatusMessage = L("Task.SubmitValidationNeedAppPath");
            LastSubmitStageLabel = StageToLabel(SubmitFailureStage.LocalContextMissing);
            LastSubmitNextSteps = BuildSubmitNextSteps(SubmitFailureStage.LocalContextMissing);
            OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
            return false;
        }

        PrepareLastSubmitPaths(_selectedTaskUnit);
        LastSubmitStatusStyleKey = "InfoTextStyle";
        LastSubmitStatusMessage = L("Task.SubmitValidationReady");
        LastSubmitStageLabel = L("Task.SubmitStageReady");
        LastSubmitNextSteps = L("Task.SubmitAdviceReady");
        OnPropertyChanged(nameof(HasLastSubmitDiagnostics));
        return true;
    }

    private void PrepareLastSubmitPaths(TaskUnitViewModel? unit)
    {
        var unitName = ResolveUnitNameForPath(unit);
        var localTaskDir = GetLocalTaskDir();
        var normalizedWorkDir = NormalizeRemotePath(ResolveWorkDirForSubmit(unit));
        LastSubmitUnitName = unit?.TaskName ?? string.Empty;
        LastSubmitRemoteWorkDir = normalizedWorkDir;
        LastSubmitRemoteStdoutPath = string.IsNullOrWhiteSpace(normalizedWorkDir) ? string.Empty : $"{normalizedWorkDir.TrimEnd('/')}/logs/job.out";
        LastSubmitRemoteStderrPath = string.IsNullOrWhiteSpace(normalizedWorkDir) ? string.Empty : $"{normalizedWorkDir.TrimEnd('/')}/logs/job.err";
        LastSubmitLocalScriptPath = Path.Combine(localTaskDir, unitName, "scripts", "submit.sbatch");
        LastSubmitLocalSubmitLogPath = Path.Combine(localTaskDir, unitName, "logs", "submit.log");
        OnPropertyChanged(nameof(LastSubmitRemoteWorkDirDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStdoutPathDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStderrPathDisplay));
    }

    private async Task OpenLastSubmitScriptAsync(CancellationToken ct)
        => await OpenLocalDiagnosticFileAsync(LastSubmitLocalScriptPath, "Task.DiagnosticScriptMissing", ct);

    private async Task OpenLastSubmitLogAsync(CancellationToken ct)
        => await OpenLocalDiagnosticFileAsync(LastSubmitLocalSubmitLogPath, "Task.DiagnosticSubmitLogMissing", ct);

    private async Task OpenLastStdoutAsync(CancellationToken ct)
    {
        await OpenRemoteDiagnosticFileAsync(LastSubmitRemoteStdoutPath, "Task.DiagnosticStdoutMissing", ct);
    }

    private async Task OpenLastStderrAsync(CancellationToken ct)
    {
        await OpenRemoteDiagnosticFileAsync(LastSubmitRemoteStderrPath, "Task.DiagnosticStderrMissing", ct);
    }

    private async Task OpenLastSubmitWorkDirInConsoleAsync(CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(LastSubmitRemoteWorkDir))
        {
            SetStatus("Task.DiagnosticWorkDirMissing", "WarningTextStyle");
            return;
        }

        if (_openInConsoleAsync == null)
        {
            SetStatus("Task.OpenInTerminalUnavailable", "WarningTextStyle");
            return;
        }

        var opened = await _openInConsoleAsync(LastSubmitRemoteWorkDir);
        SetStatus(
            opened
                ? string.Format(L("Task.OpenInTerminalSuccess"), CollapseHomePath(LastSubmitRemoteWorkDir))
                : string.Format(L("Task.OpenInTerminalFailed"), CollapseHomePath(LastSubmitRemoteWorkDir)),
            opened ? "SuccessTextStyle" : "WarningTextStyle",
            localize: false);
    }

    private async Task RefreshLastSubmitWorkDirFilesAsync(CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(LastSubmitRemoteWorkDir))
        {
            SetStatus("Task.DiagnosticWorkDirMissing", "WarningTextStyle");
            return;
        }

        CurrentTaskFilesPath = LastSubmitRemoteWorkDir;
        await RefreshTaskFilesAsync(ct);
    }

    public string GetCurrentRemoteWorkDirForDiagnostics()
        => ResolveWorkDirForSubmit(_selectedTaskUnit);

    public async Task<bool> OpenRemoteDiagnosticFileFromMonitorAsync(string remotePath, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(remotePath))
            return false;

        return await OpenRemoteDiagnosticFileAsync(remotePath, "Task.DiagnosticRemoteFileMissing", ct);
    }

    public async Task<bool> OpenDirectoryInConsoleFromMonitorAsync(string remotePath, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(remotePath) || _openInConsoleAsync == null)
            return false;

        var opened = await _openInConsoleAsync(remotePath);
        if (!opened)
            SetStatus(string.Format(L("Task.OpenInTerminalFailed"), CollapseHomePath(remotePath)), "WarningTextStyle", localize: false);
        return opened;
    }

    private async Task OpenLocalDiagnosticFileAsync(string path, string missingResourceKey, CancellationToken ct)
    {
        await Task.Yield();
        if (string.IsNullOrWhiteSpace(path))
        {
            SetStatus(string.Format(L(missingResourceKey), L("Task.DiagnosticPathUnknown")), "WarningTextStyle", localize: false);
            return;
        }

        if (!File.Exists(path))
        {
            SetStatus(string.Format(L(missingResourceKey), path), "WarningTextStyle", localize: false);
            return;
        }

        try
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = path,
                UseShellExecute = true,
            });
            SetStatus(string.Format(L("Task.DiagnosticOpenedLocalFile"), path), "SuccessTextStyle", localize: false);
        }
        catch (Exception ex)
        {
            SetStatus(string.Format(L("Task.DiagnosticOpenLocalFileFailed"), ex.Message), "ErrorTextStyle", localize: false);
        }
    }

    private async Task<bool> OpenRemoteDiagnosticFileAsync(string remotePath, string missingResourceKey, CancellationToken ct)
    {
        if (!_ssh.IsConnected)
        {
            SetStatus("Task.RequireConnection", "WarningTextStyle");
            return false;
        }

        if (string.IsNullOrWhiteSpace(remotePath))
        {
            SetStatus(string.Format(L(missingResourceKey), L("Task.DiagnosticPathUnknown")), "WarningTextStyle", localize: false);
            return false;
        }

        try
        {
            if (!await _ssh.RemoteFileExistsAsync(remotePath, ct))
            {
                SetStatus(string.Format(L(missingResourceKey), CollapseHomePath(remotePath)), "WarningTextStyle", localize: false);
                return false;
            }

            var vm = new RemoteFileEditorViewModel(_ssh, remotePath, _homeDirectory);
            var win = new RemoteFileEditorView { DataContext = vm };
            if (Application.Current.MainWindow is { } mainWin) win.Owner = mainWin;
            await vm.LoadAsync(ct);
            if (vm.IsBinaryFile)
            {
                StatusMessage = vm.StatusMessage;
                StatusStyleKey = vm.StatusStyleKey;
                return false;
            }

            win.ShowDialog();
            return true;
        }
        catch (Exception ex)
        {
            SetStatus(string.Format(L("Task.DiagnosticOpenRemoteFileFailed"), ex.Message), "ErrorTextStyle", localize: false);
            return false;
        }
    }

    private static string ResolveUnitNameForPath(TaskUnitViewModel? unit)
    {
        var name = unit?.TaskName?.Trim();
        return string.IsNullOrWhiteSpace(name) ? "default" : name;
    }

    private static bool IsConnectionRelated(Exception ex)
        => ex is TimeoutException
           || ex is OperationCanceledException
           || ex is System.Net.Sockets.SocketException
           || ex is Renci.SshNet.Common.SshAuthenticationException;

    private string StageToLabel(SubmitFailureStage stage) => stage switch
    {
        SubmitFailureStage.LocalContextMissing => L("Task.SubmitStageLocalContext"),
        SubmitFailureStage.ScriptRenderFailed => L("Task.SubmitStageRender"),
        SubmitFailureStage.SshConnectionFailed => L("Task.SubmitStageConnection"),
        SubmitFailureStage.RemoteWorkDirFailed => L("Task.SubmitStageRemoteDir"),
        SubmitFailureStage.SbatchSubmitFailed => L("Task.SubmitStageSbatchSubmit"),
        SubmitFailureStage.ParameterPathFailed => L("Task.SubmitStageParameterPath"),
        _ => L("Task.SubmitStageUnknown"),
    };

    private string BuildSubmitNextSteps(SubmitFailureStage stage) => stage switch
    {
        SubmitFailureStage.LocalContextMissing => L("Task.SubmitAdviceLocalContext"),
        SubmitFailureStage.ScriptRenderFailed => L("Task.SubmitAdviceRender"),
        SubmitFailureStage.SshConnectionFailed => L("Task.SubmitAdviceConnection"),
        SubmitFailureStage.RemoteWorkDirFailed => L("Task.SubmitAdviceRemoteDir"),
        SubmitFailureStage.SbatchSubmitFailed => L("Task.SubmitAdviceSbatch"),
        SubmitFailureStage.ParameterPathFailed => L("Task.SubmitAdviceParameterPath"),
        _ => L("Task.SubmitAdviceUnknown"),
    };

    private static string ResolveParameterPath(string? rawPath, string workDir)
    {
        if (string.IsNullOrWhiteSpace(rawPath)) return string.Empty;
        var normalized = rawPath.Trim().Replace('\\', '/');
        if (normalized.StartsWith("/", StringComparison.Ordinal))
            return normalized;
        if (string.IsNullOrWhiteSpace(workDir))
            return string.Empty;

        return $"{workDir.TrimEnd('/')}/params/{normalized}";
    }

    private static string ResolveUnitWorkDir(TaskUnitViewModel? unit)
    {
        if (unit == null) return string.Empty;
        if (!string.IsNullOrWhiteSpace(unit.RemoteWorkDirectory))
            return unit.RemoteWorkDirectory.Trim();
        return string.Empty;
    }

    private enum SubmitFailureStage
    {
        LocalContextMissing,
        ScriptRenderFailed,
        SshConnectionFailed,
        RemoteWorkDirFailed,
        SbatchSubmitFailed,
        ParameterPathFailed,
        Unknown,
    }

    private sealed class SubmitStageException : Exception
    {
        public SubmitStageException(SubmitFailureStage stage, string message, Exception? inner = null)
            : base(message, inner)
        {
            Stage = stage;
        }

        public SubmitFailureStage Stage { get; }
    }

    private string ResolveWorkDirWithFallback(TaskUnitViewModel? unit, string fallback)
    {
        var unitDir = ResolveUnitWorkDir(unit);
        if (!string.IsNullOrWhiteSpace(unitDir)) return unitDir;
        return string.IsNullOrWhiteSpace(fallback) ? string.Empty : fallback.Trim();
    }

    private string ResolveWorkDirForSubmit(TaskUnitViewModel? unit)
        => ResolveWorkDirWithFallback(unit, RemoteWorkDir);

    private static string L(string key)
        => Application.Current?.TryFindResource(key) as string ?? key;

    private async Task EnsureHomeDirectoryLoadedAsync(CancellationToken ct)
    {
        if (!_ssh.IsConnected || !string.IsNullOrWhiteSpace(_homeDirectory))
            return;

        try
        {
            var home = await _ssh.GetHomeDirectoryAsync(ct);
            if (string.IsNullOrWhiteSpace(home))
                return;

            _homeDirectory = NormalizeRemotePath(home);
            RefreshPathDisplays();
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"[TaskEditorViewModel.EnsureHomeDirectoryLoadedAsync] {ex.Message}");
        }
    }

    private void RefreshPathDisplays()
    {
        var expandedRoot = ExpandHomePath(_rootDirectory);
        if (!string.Equals(_rootDirectory, expandedRoot, StringComparison.Ordinal))
        {
            _rootDirectory = expandedRoot;
            OnPropertyChanged(nameof(RootDirectory));
        }

        var expandedWorkDir = ExpandHomePath(_remoteWorkDir);
        if (!string.Equals(_remoteWorkDir, expandedWorkDir, StringComparison.Ordinal))
        {
            _remoteWorkDir = expandedWorkDir;
            OnPropertyChanged(nameof(RemoteWorkDir));
        }

        var expandedCurrentPath = ExpandHomePath(_currentTaskFilesPath);
        if (!string.Equals(_currentTaskFilesPath, expandedCurrentPath, StringComparison.Ordinal))
        {
            _currentTaskFilesPath = expandedCurrentPath;
            OnPropertyChanged(nameof(CurrentTaskFilesPath));
        }

        OnPropertyChanged(nameof(RootDirectoryDisplay));
        OnPropertyChanged(nameof(RemoteWorkDirDisplay));
        OnPropertyChanged(nameof(CurrentTaskFilesPathDisplay));
        OnPropertyChanged(nameof(TaskFilesRootPathDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteWorkDirDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStdoutPathDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStderrPathDisplay));
    }

    private void SetStatus(string messageOrKey, string styleKey, bool localize = true)
    {
        StatusStyleKey = styleKey;
        StatusMessage = localize ? L(messageOrKey) : messageOrKey;
    }

    internal void NotifyLocaleChanged()
    {
        OnPropertyChanged(nameof(LastJobIdText));
        OnPropertyChanged(nameof(TaskIdDirectoryStatus));
        OnPropertyChanged(nameof(TaskContextSummary));
        OnPropertyChanged(nameof(EffectiveStatusMessage));
        OnPropertyChanged(nameof(LastSubmitRemoteWorkDirDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStdoutPathDisplay));
        OnPropertyChanged(nameof(LastSubmitRemoteStderrPathDisplay));
    }

    private TaskRecord BuildTaskRecord() => new()
    {
        TaskId              = TaskId,
        LocalRootDirectory  = LocalDataRoot,
        RemoteWorkDirectory = RemoteWorkDir,
        TemplateFileName    = SelectedTemplate,
        SlurmJobId          = LastJobId,
        Parameters          = Parameters
            .Where(p => !string.IsNullOrWhiteSpace(p.Key))
            .ToDictionary(p => p.Key, p => p.Value),
    };

    private void ApplyTaskRecord(TaskRecord r)
    {
        RemoteWorkDir    = r.RemoteWorkDirectory;
        CurrentTaskFilesPath = r.RemoteWorkDirectory;
        LastJobId        = r.SlurmJobId;
        SelectedTemplate = r.TemplateFileName;
        Parameters.Clear();
        foreach (var (k, v) in r.Parameters)
            Parameters.Add(new ParameterEntry { Key = k, Value = v });
    }

    private static string NormalizeRemotePath(string? path)
        => RemotePathDisplayHelper.NormalizeRemotePath(path);

    private string ExpandHomePath(string? path)
        => RemotePathDisplayHelper.ExpandHomePath(path, _homeDirectory);

    private string CollapseHomePath(string? path)
        => RemotePathDisplayHelper.CollapseHomePath(path, _homeDirectory);

    private static string BuildRemotePath(string currentPath, string itemName)
    {
        var prefix = NormalizeRemotePath(currentPath);
        if (prefix == "/") return $"/{itemName}";
        return $"{prefix}/{itemName}";
    }

    private static string EscapeShellArg(string arg)
        => "'" + arg.Replace("'", "'\\''") + "'";

    public void Dispose()
    {
        _taskIdValidationCts?.Cancel();
        _taskIdValidationCts?.Dispose();
        _taskIdValidationCts = null;
    }

    // ── Default sbatch template ──────────────────────────────────────────────

    private const string DefaultSbatchTemplate =
        "#!/bin/bash\n" +
        "#SBATCH --job-name={{JOB_NAME}}\n" +
        "#SBATCH --output={{STDOUT_FILE}}\n" +
        "#SBATCH --error={{STDERR_FILE}}\n" +
        "#SBATCH --chdir={{WORK_DIR}}\n" +
        "#SBATCH --ntasks=1\n" +
        "#SBATCH --cpus-per-task=1\n" +
        "#SBATCH --time=01:00:00\n" +
        "\n" +
        "echo \"Starting job {{JOB_NAME}} at $(date)\"\n" +
        "{{APP_PATH}} {{PARAM_FILE}}\n" +
        "echo \"Job finished at $(date)\"\n";
}

/// <summary>A single editable parameter key/value pair.</summary>
public sealed class ParameterEntry : ViewModelBase
{
    private string _key = string.Empty;
    private string _value = string.Empty;
    public string Key   { get => _key;   set => SetField(ref _key, value); }
    public string Value { get => _value; set => SetField(ref _value, value); }
}

public sealed class TaskFileEntry
{
    public TaskFileEntry(string name, bool isDirectory, string remotePath, string? displayRemotePath = null)
    {
        Name = name;
        IsDirectory = isDirectory;
        RemotePath = remotePath;
        DisplayRemotePath = string.IsNullOrWhiteSpace(displayRemotePath) ? remotePath : displayRemotePath;
    }

    public string Name { get; }
    public bool IsDirectory { get; }
    public string RemotePath { get; }
    public string DisplayRemotePath { get; }
    public string DisplayName => IsDirectory ? $"{Name}/" : Name;
}
