<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>SlurmJobManager.App</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>Assets\AppIcon\server-palm.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlurmJobManager.Core\SlurmJobManager.Core.csproj" />
    <ProjectReference Include="..\SlurmJobManager.Infrastructure\SlurmJobManager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="XTerm.NET" Version="1.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon\server-palm.ico" />
  </ItemGroup>
</Project>
